package com.bitell.model;

import java.io.Serializable;
import java.util.Date;

public class CSubjects implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.id
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.sub_name
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private String subName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.sub_icon
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private String subIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.sub_des
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private String subDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.sub_admin
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Integer subAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.create_user
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.create_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.last_modify_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_subjects.is_delete
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_subjects
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.id
     *
     * @return the value of c_subjects.id
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.id
     *
     * @param id the value for c_subjects.id
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.sub_name
     *
     * @return the value of c_subjects.sub_name
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.sub_name
     *
     * @param subName the value for c_subjects.sub_name
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setSubName(String subName) {
        this.subName = subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.sub_icon
     *
     * @return the value of c_subjects.sub_icon
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public String getSubIcon() {
        return subIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.sub_icon
     *
     * @param subIcon the value for c_subjects.sub_icon
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setSubIcon(String subIcon) {
        this.subIcon = subIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.sub_des
     *
     * @return the value of c_subjects.sub_des
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public String getSubDes() {
        return subDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.sub_des
     *
     * @param subDes the value for c_subjects.sub_des
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setSubDes(String subDes) {
        this.subDes = subDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.sub_admin
     *
     * @return the value of c_subjects.sub_admin
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Integer getSubAdmin() {
        return subAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.sub_admin
     *
     * @param subAdmin the value for c_subjects.sub_admin
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setSubAdmin(Integer subAdmin) {
        this.subAdmin = subAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.create_user
     *
     * @return the value of c_subjects.create_user
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.create_user
     *
     * @param createUser the value for c_subjects.create_user
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.create_time
     *
     * @return the value of c_subjects.create_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.create_time
     *
     * @param createTime the value for c_subjects.create_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.last_modify_time
     *
     * @return the value of c_subjects.last_modify_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.last_modify_time
     *
     * @param lastModifyTime the value for c_subjects.last_modify_time
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_subjects.is_delete
     *
     * @return the value of c_subjects.is_delete
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_subjects.is_delete
     *
     * @param isDelete the value for c_subjects.is_delete
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_subjects
     *
     * @mbg.generated Mon Mar 26 20:56:35 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subName=").append(subName);
        sb.append(", subIcon=").append(subIcon);
        sb.append(", subDes=").append(subDes);
        sb.append(", subAdmin=").append(subAdmin);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastModifyTime=").append(lastModifyTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }
}