package com.bitell.mapper;

import com.bitell.model.ArticleSubRef;
import com.bitell.model.ArticleSubRefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleSubRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    long countByExample(ArticleSubRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int deleteByExample(ArticleSubRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int insert(ArticleSubRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int insertSelective(ArticleSubRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    List<ArticleSubRef> selectByExample(ArticleSubRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    ArticleSubRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleSubRef record, @Param("example") ArticleSubRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByExample(@Param("record") ArticleSubRef record, @Param("example") ArticleSubRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleSubRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_sub_ref
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByPrimaryKey(ArticleSubRef record);
}