package com.bitell.mapper;

import com.bitell.model.CArticlesForwards;
import com.bitell.model.CArticlesForwardsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CArticlesForwardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    long countByExample(CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int deleteByExample(CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int insert(CArticlesForwards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int insertSelective(CArticlesForwards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    List<CArticlesForwards> selectByExampleWithBLOBs(CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    List<CArticlesForwards> selectByExample(CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    CArticlesForwards selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") CArticlesForwards record, @Param("example") CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CArticlesForwards record, @Param("example") CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByExample(@Param("record") CArticlesForwards record, @Param("example") CArticlesForwardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByPrimaryKeySelective(CArticlesForwards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CArticlesForwards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles_forwards
     *
     * @mbg.generated Sat Mar 31 13:58:28 CST 2018
     */
    int updateByPrimaryKey(CArticlesForwards record);
}