package com.bitell.mapper;

import com.bitell.model.CArticles;
import com.bitell.model.CArticlesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    long countByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int deleteByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int insert(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int insertSelective(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    List<CArticles> selectByExampleWithBLOBs(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    List<CArticles> selectByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    CArticles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByExample(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByPrimaryKeySelective(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 20:30:33 CST 2018
     */
    int updateByPrimaryKey(CArticles record);
}