package com.bitell.mapper;

import com.bitell.model.CLikes;
import com.bitell.model.CLikesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CLikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    long countByExample(CLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int deleteByExample(CLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int insert(CLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int insertSelective(CLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    List<CLikes> selectByExample(CLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    CLikes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") CLikes record, @Param("example") CLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByExample(@Param("record") CLikes record, @Param("example") CLikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByPrimaryKeySelective(CLikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Mon Mar 26 19:16:19 CST 2018
     */
    int updateByPrimaryKey(CLikes record);
}