package com.bitell.entity;

import com.bitell.base.ApiRequest;

import java.util.Date;

/**
* Company:千山健康
* Author:an.huang
* Date:2018/3/26
*/
public class ArticlePublishRequest extends ApiRequest{
    private Long id;

    private Integer authorId;

    private String authorType;

    private String title;

    private String subIds;

    private Byte isDelete;

    private Byte status;

    private Date createTime;

    private Date pubTime;

    private String coverImg1Url;

    private String coverImg2Url;

    private String coverImg3Url;

    private String coverImg4Url;

    private String coverImg5Url;

    private String coverImg6Url;

    private String coverImg7Url;

    private String coverImg8Url;

    private String coverImg9Url;

    private String videoUrl;

    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_articles.content_text
     *
     * @mbg.generated Mon Mar 26 15:43:57 CST 2018
     */
    private String contentText;
}
