package com.bitell.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CArticlesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public CArticlesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIsNull() {
            addCriterion("author_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIsNotNull() {
            addCriterion("author_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorIdEqualTo(Integer value) {
            addCriterion("author_id =", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotEqualTo(Integer value) {
            addCriterion("author_id <>", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdGreaterThan(Integer value) {
            addCriterion("author_id >", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("author_id >=", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdLessThan(Integer value) {
            addCriterion("author_id <", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdLessThanOrEqualTo(Integer value) {
            addCriterion("author_id <=", value, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdIn(List<Integer> values) {
            addCriterion("author_id in", values, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotIn(List<Integer> values) {
            addCriterion("author_id not in", values, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdBetween(Integer value1, Integer value2) {
            addCriterion("author_id between", value1, value2, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("author_id not between", value1, value2, "authorId");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIsNull() {
            addCriterion("author_type is null");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIsNotNull() {
            addCriterion("author_type is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeEqualTo(String value) {
            addCriterion("author_type =", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotEqualTo(String value) {
            addCriterion("author_type <>", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeGreaterThan(String value) {
            addCriterion("author_type >", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("author_type >=", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLessThan(String value) {
            addCriterion("author_type <", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLessThanOrEqualTo(String value) {
            addCriterion("author_type <=", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLike(String value) {
            addCriterion("author_type like", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotLike(String value) {
            addCriterion("author_type not like", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIn(List<String> values) {
            addCriterion("author_type in", values, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotIn(List<String> values) {
            addCriterion("author_type not in", values, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeBetween(String value1, String value2) {
            addCriterion("author_type between", value1, value2, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotBetween(String value1, String value2) {
            addCriterion("author_type not between", value1, value2, "authorType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeIsNull() {
            addCriterion("pub_time is null");
            return (Criteria) this;
        }

        public Criteria andPubTimeIsNotNull() {
            addCriterion("pub_time is not null");
            return (Criteria) this;
        }

        public Criteria andPubTimeEqualTo(Date value) {
            addCriterion("pub_time =", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotEqualTo(Date value) {
            addCriterion("pub_time <>", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeGreaterThan(Date value) {
            addCriterion("pub_time >", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pub_time >=", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeLessThan(Date value) {
            addCriterion("pub_time <", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeLessThanOrEqualTo(Date value) {
            addCriterion("pub_time <=", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeIn(List<Date> values) {
            addCriterion("pub_time in", values, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotIn(List<Date> values) {
            addCriterion("pub_time not in", values, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeBetween(Date value1, Date value2) {
            addCriterion("pub_time between", value1, value2, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotBetween(Date value1, Date value2) {
            addCriterion("pub_time not between", value1, value2, "pubTime");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlIsNull() {
            addCriterion("cover_img1_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlIsNotNull() {
            addCriterion("cover_img1_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlEqualTo(String value) {
            addCriterion("cover_img1_url =", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlNotEqualTo(String value) {
            addCriterion("cover_img1_url <>", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlGreaterThan(String value) {
            addCriterion("cover_img1_url >", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img1_url >=", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlLessThan(String value) {
            addCriterion("cover_img1_url <", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img1_url <=", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlLike(String value) {
            addCriterion("cover_img1_url like", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlNotLike(String value) {
            addCriterion("cover_img1_url not like", value, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlIn(List<String> values) {
            addCriterion("cover_img1_url in", values, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlNotIn(List<String> values) {
            addCriterion("cover_img1_url not in", values, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlBetween(String value1, String value2) {
            addCriterion("cover_img1_url between", value1, value2, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg1UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img1_url not between", value1, value2, "coverImg1Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlIsNull() {
            addCriterion("cover_img2_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlIsNotNull() {
            addCriterion("cover_img2_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlEqualTo(String value) {
            addCriterion("cover_img2_url =", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlNotEqualTo(String value) {
            addCriterion("cover_img2_url <>", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlGreaterThan(String value) {
            addCriterion("cover_img2_url >", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img2_url >=", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlLessThan(String value) {
            addCriterion("cover_img2_url <", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img2_url <=", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlLike(String value) {
            addCriterion("cover_img2_url like", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlNotLike(String value) {
            addCriterion("cover_img2_url not like", value, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlIn(List<String> values) {
            addCriterion("cover_img2_url in", values, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlNotIn(List<String> values) {
            addCriterion("cover_img2_url not in", values, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlBetween(String value1, String value2) {
            addCriterion("cover_img2_url between", value1, value2, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg2UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img2_url not between", value1, value2, "coverImg2Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlIsNull() {
            addCriterion("cover_img3_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlIsNotNull() {
            addCriterion("cover_img3_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlEqualTo(String value) {
            addCriterion("cover_img3_url =", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlNotEqualTo(String value) {
            addCriterion("cover_img3_url <>", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlGreaterThan(String value) {
            addCriterion("cover_img3_url >", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img3_url >=", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlLessThan(String value) {
            addCriterion("cover_img3_url <", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img3_url <=", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlLike(String value) {
            addCriterion("cover_img3_url like", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlNotLike(String value) {
            addCriterion("cover_img3_url not like", value, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlIn(List<String> values) {
            addCriterion("cover_img3_url in", values, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlNotIn(List<String> values) {
            addCriterion("cover_img3_url not in", values, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlBetween(String value1, String value2) {
            addCriterion("cover_img3_url between", value1, value2, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg3UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img3_url not between", value1, value2, "coverImg3Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlIsNull() {
            addCriterion("cover_img4_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlIsNotNull() {
            addCriterion("cover_img4_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlEqualTo(String value) {
            addCriterion("cover_img4_url =", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlNotEqualTo(String value) {
            addCriterion("cover_img4_url <>", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlGreaterThan(String value) {
            addCriterion("cover_img4_url >", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img4_url >=", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlLessThan(String value) {
            addCriterion("cover_img4_url <", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img4_url <=", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlLike(String value) {
            addCriterion("cover_img4_url like", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlNotLike(String value) {
            addCriterion("cover_img4_url not like", value, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlIn(List<String> values) {
            addCriterion("cover_img4_url in", values, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlNotIn(List<String> values) {
            addCriterion("cover_img4_url not in", values, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlBetween(String value1, String value2) {
            addCriterion("cover_img4_url between", value1, value2, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg4UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img4_url not between", value1, value2, "coverImg4Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlIsNull() {
            addCriterion("cover_img5_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlIsNotNull() {
            addCriterion("cover_img5_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlEqualTo(String value) {
            addCriterion("cover_img5_url =", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlNotEqualTo(String value) {
            addCriterion("cover_img5_url <>", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlGreaterThan(String value) {
            addCriterion("cover_img5_url >", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img5_url >=", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlLessThan(String value) {
            addCriterion("cover_img5_url <", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img5_url <=", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlLike(String value) {
            addCriterion("cover_img5_url like", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlNotLike(String value) {
            addCriterion("cover_img5_url not like", value, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlIn(List<String> values) {
            addCriterion("cover_img5_url in", values, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlNotIn(List<String> values) {
            addCriterion("cover_img5_url not in", values, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlBetween(String value1, String value2) {
            addCriterion("cover_img5_url between", value1, value2, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg5UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img5_url not between", value1, value2, "coverImg5Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlIsNull() {
            addCriterion("cover_img6_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlIsNotNull() {
            addCriterion("cover_img6_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlEqualTo(String value) {
            addCriterion("cover_img6_url =", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlNotEqualTo(String value) {
            addCriterion("cover_img6_url <>", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlGreaterThan(String value) {
            addCriterion("cover_img6_url >", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img6_url >=", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlLessThan(String value) {
            addCriterion("cover_img6_url <", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img6_url <=", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlLike(String value) {
            addCriterion("cover_img6_url like", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlNotLike(String value) {
            addCriterion("cover_img6_url not like", value, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlIn(List<String> values) {
            addCriterion("cover_img6_url in", values, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlNotIn(List<String> values) {
            addCriterion("cover_img6_url not in", values, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlBetween(String value1, String value2) {
            addCriterion("cover_img6_url between", value1, value2, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg6UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img6_url not between", value1, value2, "coverImg6Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlIsNull() {
            addCriterion("cover_img7_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlIsNotNull() {
            addCriterion("cover_img7_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlEqualTo(String value) {
            addCriterion("cover_img7_url =", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlNotEqualTo(String value) {
            addCriterion("cover_img7_url <>", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlGreaterThan(String value) {
            addCriterion("cover_img7_url >", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img7_url >=", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlLessThan(String value) {
            addCriterion("cover_img7_url <", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img7_url <=", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlLike(String value) {
            addCriterion("cover_img7_url like", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlNotLike(String value) {
            addCriterion("cover_img7_url not like", value, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlIn(List<String> values) {
            addCriterion("cover_img7_url in", values, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlNotIn(List<String> values) {
            addCriterion("cover_img7_url not in", values, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlBetween(String value1, String value2) {
            addCriterion("cover_img7_url between", value1, value2, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg7UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img7_url not between", value1, value2, "coverImg7Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlIsNull() {
            addCriterion("cover_img8_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlIsNotNull() {
            addCriterion("cover_img8_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlEqualTo(String value) {
            addCriterion("cover_img8_url =", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlNotEqualTo(String value) {
            addCriterion("cover_img8_url <>", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlGreaterThan(String value) {
            addCriterion("cover_img8_url >", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img8_url >=", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlLessThan(String value) {
            addCriterion("cover_img8_url <", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img8_url <=", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlLike(String value) {
            addCriterion("cover_img8_url like", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlNotLike(String value) {
            addCriterion("cover_img8_url not like", value, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlIn(List<String> values) {
            addCriterion("cover_img8_url in", values, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlNotIn(List<String> values) {
            addCriterion("cover_img8_url not in", values, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlBetween(String value1, String value2) {
            addCriterion("cover_img8_url between", value1, value2, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg8UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img8_url not between", value1, value2, "coverImg8Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlIsNull() {
            addCriterion("cover_img9_url is null");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlIsNotNull() {
            addCriterion("cover_img9_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlEqualTo(String value) {
            addCriterion("cover_img9_url =", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlNotEqualTo(String value) {
            addCriterion("cover_img9_url <>", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlGreaterThan(String value) {
            addCriterion("cover_img9_url >", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlGreaterThanOrEqualTo(String value) {
            addCriterion("cover_img9_url >=", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlLessThan(String value) {
            addCriterion("cover_img9_url <", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlLessThanOrEqualTo(String value) {
            addCriterion("cover_img9_url <=", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlLike(String value) {
            addCriterion("cover_img9_url like", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlNotLike(String value) {
            addCriterion("cover_img9_url not like", value, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlIn(List<String> values) {
            addCriterion("cover_img9_url in", values, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlNotIn(List<String> values) {
            addCriterion("cover_img9_url not in", values, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlBetween(String value1, String value2) {
            addCriterion("cover_img9_url between", value1, value2, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andCoverImg9UrlNotBetween(String value1, String value2) {
            addCriterion("cover_img9_url not between", value1, value2, "coverImg9Url");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlIsNull() {
            addCriterion("source_url is null");
            return (Criteria) this;
        }

        public Criteria andSourceUrlIsNotNull() {
            addCriterion("source_url is not null");
            return (Criteria) this;
        }

        public Criteria andSourceUrlEqualTo(String value) {
            addCriterion("source_url =", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlNotEqualTo(String value) {
            addCriterion("source_url <>", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlGreaterThan(String value) {
            addCriterion("source_url >", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("source_url >=", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlLessThan(String value) {
            addCriterion("source_url <", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlLessThanOrEqualTo(String value) {
            addCriterion("source_url <=", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlLike(String value) {
            addCriterion("source_url like", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlNotLike(String value) {
            addCriterion("source_url not like", value, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlIn(List<String> values) {
            addCriterion("source_url in", values, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlNotIn(List<String> values) {
            addCriterion("source_url not in", values, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlBetween(String value1, String value2) {
            addCriterion("source_url between", value1, value2, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andSourceUrlNotBetween(String value1, String value2) {
            addCriterion("source_url not between", value1, value2, "sourceUrl");
            return (Criteria) this;
        }

        public Criteria andForwardIdIsNull() {
            addCriterion("forward_id is null");
            return (Criteria) this;
        }

        public Criteria andForwardIdIsNotNull() {
            addCriterion("forward_id is not null");
            return (Criteria) this;
        }

        public Criteria andForwardIdEqualTo(Long value) {
            addCriterion("forward_id =", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdNotEqualTo(Long value) {
            addCriterion("forward_id <>", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdGreaterThan(Long value) {
            addCriterion("forward_id >", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdGreaterThanOrEqualTo(Long value) {
            addCriterion("forward_id >=", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdLessThan(Long value) {
            addCriterion("forward_id <", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdLessThanOrEqualTo(Long value) {
            addCriterion("forward_id <=", value, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdIn(List<Long> values) {
            addCriterion("forward_id in", values, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdNotIn(List<Long> values) {
            addCriterion("forward_id not in", values, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdBetween(Long value1, Long value2) {
            addCriterion("forward_id between", value1, value2, "forwardId");
            return (Criteria) this;
        }

        public Criteria andForwardIdNotBetween(Long value1, Long value2) {
            addCriterion("forward_id not between", value1, value2, "forwardId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_articles
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 30 21:17:25 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_articles
     *
     * @mbg.generated Fri Mar 30 21:17:25 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}