package com.bitell.model;

import java.io.Serializable;

public class CArticleCount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article_count.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article_count.likes
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article_count.comments
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Integer comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article_count.shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Integer shareds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article_count.article_id
     *
     * @return the value of c_article_count.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article_count.article_id
     *
     * @param articleId the value for c_article_count.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article_count.likes
     *
     * @return the value of c_article_count.likes
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article_count.likes
     *
     * @param likes the value for c_article_count.likes
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article_count.comments
     *
     * @return the value of c_article_count.comments
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article_count.comments
     *
     * @param comments the value for c_article_count.comments
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article_count.shareds
     *
     * @return the value of c_article_count.shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Integer getShareds() {
        return shareds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article_count.shareds
     *
     * @param shareds the value for c_article_count.shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setShareds(Integer shareds) {
        this.shareds = shareds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", likes=").append(likes);
        sb.append(", comments=").append(comments);
        sb.append(", shareds=").append(shareds);
        sb.append("]");
        return sb.toString();
    }
}