package com.bitell.model;

import java.io.Serializable;
import java.util.Date;

public class CLikes implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_likes.id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_likes.user_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_likes.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_likes.create_time
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_likes
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_likes.id
     *
     * @return the value of c_likes.id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_likes.id
     *
     * @param id the value for c_likes.id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_likes.user_id
     *
     * @return the value of c_likes.user_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_likes.user_id
     *
     * @param userId the value for c_likes.user_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_likes.article_id
     *
     * @return the value of c_likes.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_likes.article_id
     *
     * @param articleId the value for c_likes.article_id
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_likes.create_time
     *
     * @return the value of c_likes.create_time
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_likes.create_time
     *
     * @param createTime the value for c_likes.create_time
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_likes
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", articleId=").append(articleId);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}