package com.bitell.mapper;

import com.bitell.entity.articles.vo.AritcleCountVo;
import com.bitell.model.CArticleCount;
import com.bitell.model.CArticleCountExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CArticleCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    long countByExample(CArticleCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int deleteByExample(CArticleCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insert(CArticleCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insertSelective(CArticleCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    List<CArticleCount> selectByExample(CArticleCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") CArticleCount record, @Param("example") CArticleCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article_count
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExample(@Param("record") CArticleCount record, @Param("example") CArticleCountExample example);

    /**
     * 根据文章id查询文章相关的点赞、评论、分享数量
    * Author:an.huang
    * Descriptions:
    * Date:2018/3/27
    */
    AritcleCountVo selectByArticleId(Long id);
}