package com.bitell.mapper;

import com.bitell.entity.articles.vo.ArticlesQueryVo;
import com.bitell.model.CArticles;
import com.bitell.model.CArticlesExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    long countByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int deleteByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insert(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insertSelective(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    List<CArticles> selectByExampleWithBLOBs(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    List<CArticles> selectByExample(CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    CArticles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExample(@Param("record") CArticles record, @Param("example") CArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByPrimaryKeySelective(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_articles
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByPrimaryKey(CArticles record);

    /**
     * 分页查询文章内容
    * Author:an.huang
    * Descriptions:
    * Date:2018/3/27
    */
    List<ArticlesQueryVo> selectByPage(Map<String,Object> map);
}