package com.bitell.mapper;

import com.bitell.model.CShareds;
import com.bitell.model.CSharedsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CSharedsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    long countByExample(CSharedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int deleteByExample(CSharedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insert(CShareds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int insertSelective(CShareds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    List<CShareds> selectByExample(CSharedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    CShareds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") CShareds record, @Param("example") CSharedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByExample(@Param("record") CShareds record, @Param("example") CSharedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByPrimaryKeySelective(CShareds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shareds
     *
     * @mbg.generated Tue Mar 27 10:50:56 CST 2018
     */
    int updateByPrimaryKey(CShareds record);
}